alias: Awtrix Notification Spotify by Zoker
description: Based on the Spotify Song Notification Flow by Zoker
triggers:
  - entity_id:
      - media_player.spotify
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.spotify
            state:
              - idle
              - paused
        sequence:
          - action: awtrix.delete_custom_app
            metadata: {}
            data:
              device: <Your Awtrix device>
              app: Spotify
      - conditions:
          - condition: state
            entity_id: media_player.spotify
            state:
              - playing
        sequence:
          - action: awtrix.custom_app
            metadata: {}
            data:
              device: <Your Awtrix device>
              app: Spotify
              icon: "43961"
              text: >-
                {{states.media_player.spotify.attributes.media_artist}}
                -
                {{states.media_player.spotify.attributes.media_title}}
              pushIcon: "0"
              duration: 10
            enabled: true
mode: single
